### ISSUE TITLE
accountID can't be datatype and object property

### ISSUE THREAD

**Issue by np00** [vocol/salesforce#1]
Those classes are disjoint [1]. If you want to allow both, pointing to some "text id" and actually "account class", I recommend to create 2x different properties. 

Where:
     https://github.com/vocol/salesforce/blob/master/Contact.ttl#L8

[1] https://www.w3.org/TR/owl-ref/#OWLDL

**Comment by am29d** [comment]
Agree. most "Id"-poprieties are too salesforce specific, so removed them for now. Besides, Account object is not important to keep it in the model. 

Fixed with 05271db4e6b3a6ab4af9bccb50935c91ded878e9
