### ISSUE TITLE
Specify the language for rdfs:label

### ISSUE THREAD

**Issue by np00** [vocol/salesforce#3]
Where: Every rdfs:label

Problem: 
`rdfs:label "Assistant's Name"^^xsd:string ;`

I am not 100% sure about it, but even though it might not be wrong, I would not specify here that the value of rdfs:label is a xsd:string. I would rather add the language, such as: 

`rdfs:label "Assistant's Name"@en ;`

Please keep it open, I would like to have a college looking it at too. Would be interested in the final answer ;)

**Comment by clange** [comment]
`"foo"^^xsd:string` is equivalent to `"foo"`, i.e. a string literal with language unspecified. But I agree, labels are meant for consumption by humans (e.g. by displaying them on a UI), and humans speak languages, so indeed labels should preferably have a language tag.

**Comment by np00** [comment]
Apparently, a language tag implies that the value is of type rdf:langstring. Thus, making an explicit definition unnecessary and at the same time prevent faulty usage. See also: https://www.w3.org/TR/rdf11-concepts/#section-Datatypes

**Comment by am29d** [comment]
Labels have now a language tag instead of string. See 1d03bf9ba508b45c933c7dbec415f11bb977af01
