### ISSUE TITLE
Fix range when multiple concepts are involved

### ISSUE THREAD

**Issue by np00** [vocol/salesforce#7]
Problem: 
`rdfs:range rdfs:Literal,
        sf:Pricebook2 .`
This statement implies that 'rdfs:Literal' and 'sf:Pricebook2' are the same thing.

There are 2x ways to specify that a domain or a range have multiple classes. One is to create an "abstract superclass" which combines all these concepts. Another is to use 'owl:unionOf' (my preference)   See: https://github.com/vocol/scor/blob/master/scor.ttl#L4315

**Comment by am29d** [comment]
the rdfs:Literal statement was reduntant. With Fixed #2 I've removed that part so it should be correct now.
